# 4) გამოიყენეთ print ფუნქცია და დაბეჭდეთ თქვენთვის სასურველი მნიშვნელობები 20-ჯერ.

print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
print("goa")
